# Generated by Django 4.0.6 on 2022-07-30 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adress_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=14)),
                ('long', models.DecimalField(decimal_places=6, max_digits=14)),
                ('contact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
    ]
